### ISSUE TITLE
Sunbeam cluster bootstrap fails due to Invalid provider registry host

### ISSUE THREAD

**Issue by leozaur1808** [openstack-snaps/sunbeam-terraform#33]
When running `sunbeam cluster bootstrap ` command on a new machine after all previous steps on the [microstack website](https://ubuntu.com/openstack/install#single-multi-large-cluster) have been completed, the command fails with the following output: 
```
terraform init failed: 
Initializing the backend...

Initializing provider plugins...
- Finding juju/juju versions matching ">= 0.7.0"...


Error: Invalid provider registry host

The host "registry.terraform.io" given in in provider source address
"registry.terraform.io/juju/juju" does not offer a Terraform provider
registry.


Error: Command '['/snap/openstack/188/bin/terraform', 'init', '-upgrade', '-no-color']' returned non-zero exit status 1.
```

A possible explanation is that a registry.terraform.io is not available in my region. I addressed this issue by creating a .terraformrc file inside a user's home directory with mirror configuration. Here are the contents of this file:
```
provider_installation {
  network_mirror {
    url     = "https://nm.tf.org.ru/"
    include = ["registry.terraform.io/*/*"]
  }
  direct {
    exclude = ["registry.terraform.io/*/*"]
  }
}
```

Nonetheless, the error message remains the same and nothing changes. I believe this issue should be addressed especially for those running sunbeam in a secure environment where the terraform registry is not available. Thanks in advance.

**Comment by gboutry** [comment]
Thank you for opening an issue, Launchpad is the preferred issue tracker.

I see you already opened [a bug there](https://bugs.launchpad.net/snap-openstack/+bug/2024312), so I'm gonna close it here.
